### ISSUE TITLE
No markdown visibility with Firefox

### ISSUE THREAD

**Issue by J-Jamet** [zerodevx/zero-md#19] opened 2019-10-07 08:29 UTC
Zero-md doesnt work with Firefox.

![Screenshot from 2019-10-07 10-26-37](https://user-images.githubusercontent.com/19224038/66296086-117feb80-e8ed-11e9-9cbc-b94d40aa33d9.png)

(Tested with Firefox 60.9 on Debian 9)

**Comment by zerodevx** [comment] 2019-10-07 09:08
Hi, thanks for the bug report. I believe this issue is caused by [`webcomponentsjs`](https://github.com/webcomponents/polyfills/tree/master/packages/webcomponentsjs). The underlying tech for `zero-md` is [Web Components v1](https://github.com/w3c/webcomponents) - this spec is implemented natively in Firefox from [v63](https://caniuse.com/#feat=custom-elementsv1) (we are at Firefox v69 now - which I just tested and seems fine). However I'm quite surprised that you're encountering this issue... the whole point of `webcomponentsjs` is to polyfill browsers (like Firefox v62 and below) so that web components work.

`zero-md` has been working for a few years now, even on Firefox <v63 with `webcomponentsjs`, so I'm inclined to believe that there is a regression in the `webcomponentsjs` repo that happened recently. Let me dive deeper into this soon.

**Comment by zerodevx** [comment] 2019-10-08 09:52
@J-Jamet From your screenshot, I assume you visited the page: https://zerodevx.github.io/zero-md/ ?

**Comment by J-Jamet** [comment] 2019-10-08 10:06
Yes exactly, I did not understand why there was just a blank screen until I checked on Chromium (works on it). That's how I detected the bug.
In any case I love this project. This will be very handy for making github documentations that fit into static sites.

**Comment by zerodevx** [comment] 2019-10-09 08:44
Glad this helps. 😄 

Now I'm quite certain this issue is due to a regression in the Custom Elements polyfills [here](https://github.com/webcomponents/polyfills/tree/master/packages/webcomponentsjs/src/entrypoints). I'll have to take this up (or raise a PR) to Google's Web Components team - but because the team's general stand is to support the *last 3 major* revisions of browsers, it's not guaranteed that they will fix. 😦 

In the meantime, is it possible for you to upgrade your version of Firefox? We are at Firefox v69 now, and the Custom Element polyfill isn't needed from v63 onwards.

**Comment by J-Jamet** [comment] 2019-10-09 09:32
Personally it does not trouble me, it's only for debian stable users who are looking at documentation. This is the ESR version of firefox that is impacted, we must wait for the next stable version. https://packages.debian.org/search?keywords=firefox

**Comment by zerodevx** [comment] 2019-10-10 06:05
Ah I get what you mean. Let's keep this issue open for now while I see what can be done.

**Comment by dubiouscript** [comment] 2019-10-26 09:00
thanks for opening / looking into this !!!

>certain this issue is due to a regression in the Custom Elements polyfills here. I'll have to take this up (or raise a PR) to Google's Web Components team - but because the team's general stand is to support the last 3 major revisions of browsers, it's not guaranteed that they will fix. 😦

:disappointed: 

... after a moment of doubting my sanity   
i had not known/considered minor version bumps 
would be a feature of using the url linking "webcomponentsjs@2"

ftr this "fixed" it for me 
 ..the scripts started working again =] *applause*

```
    <!-- 
    <script src="https://cdn.jsdelivr.net/npm/@webcomponents/webcomponentsjs@2/webcomponents-loader.min.js"></script> 
    -->
  <script src="https://cdn.jsdelivr.net/npm/@webcomponents/webcomponentsjs@2.2.10/webcomponents-loader.js"></script> 


```

**Comment by zerodevx** [comment] 2019-10-27 08:40
Hi @dubiouscript, thanks for looking into this! Great idea to pin to an older version of `webcomponentsjs` - at least until the regression is resolved. Thanks! 👍

**Comment by J-Jamet** [comment] 2019-10-27 15:46
Thanks @dubiouscript this hotfix works very well.

**Comment by zerodevx** [comment] 2020-11-02 10:45
So it's been another year 😄  - shadow dom is natively supported since last 3 major browser versions ago, so consequently there is less need for polyfills...? 🤞 

If legacy support is needed: https://zerodevx.github.io/zero-md/advanced-usage/

Closing this for now!

**Closed by zerodevx** 2020-11-02 10:45 UTC
