### ISSUE TITLE
Code Highlighting not working in java code 

### ISSUE THREAD

**Issue by subhendumondal** [zerodevx/zero-md#23] opened 2020-02-20 04:06 UTC
Java Code highlighting is not working, can please check this issue
![image](https://user-images.githubusercontent.com/29480910/74900012-792e6300-53c4-11ea-9aea-e7e48381ce32.png)

**Comment by zerodevx** [comment] 2020-02-20 09:34
Have you tried hinting the language in your markdown? Like:

```java

```java
... 
my java code 
...

```

**Comment by sewbacca** [comment] 2020-03-21 10:38
I have the same problem but with python. I have hinted at and also tried json for a test. Both didn't work, it displays it as plain old text.

**Comment by zerodevx** [comment] 2020-03-22 14:02
Ah I see. This will be fixed in the next release. Will keep this open for now. Thanks!

**Comment by bennypowers** [comment] 2020-05-15 13:23
@zerodevx should make `prismPlugins: String[]` customizable on `window.ZeroMd`, so users can choose their preferred cdn

**Comment by zerodevx** [comment] 2020-06-09 07:58
Yup, the problem is at the current version, a super-simplistic shim is used to provide some form of "language detection". This needs to be override-able in future.

**Comment by zerodevx** [comment] 2020-11-02 10:58
V2 is released and has in-built support for >200 languages. So as long as your code block *hints* the language, things *should just work*. 😄 

```
    ```java
    // Hint the language after triple-backticks
    ```
```

Closing this for now! 🎉  Feel free to re-open if something's wrong!

**Closed by zerodevx** 2020-11-02 10:58 UTC
