### ISSUE TITLE
relative md links not working when in subdirectories

### ISSUE THREAD

**Issue by fbalady-synamedia** [zerodevx/zero-md#22] opened 2020-02-13 16:08 UTC
If I have the following md directory structure:

/var/www/html/docs/
/var/www/html/docs/index.html
/var/www/html/docs/test/
/var/www/html/docs/test/top.md
/var/www/html/docs/test/subdir/
/var/www/html/docs/test/subdir/subdir.md

With index.html contains:
`<zero-md src="test/top.md"></zero-md>`

And top.md contains:
`[subdir](subdir/subdir.md)`

Then when browsing to "http://<domain.com>/docs/"
the "subdir" link in the zero-md rendered html of top.md incorrectly points to:  http://<domain.com>/docs/subdir/subdir.md

whereas the "subdir" link should point to:  http://<domain.com>/docs/test/subdir/subdir.md
so there is a missing path sub dir of "test"

**Comment by zerodevx** [comment] 2020-02-14 14:32
Hi there - I'm of the opinion that this is expected behaviour. What rendering does is that it simply copies the link path as described in the markdown. `zero-md` transforming that path is likely to lead to side-effects and unintended consequences. 

A suggestion is to write your links in *absolute* paths; like

`[subdir](https://example.com/docs/test/subdir/subdir.md)`

(btw, why is the link to a `.md` file though?)

Alternatively, you might want to handle link transformation yourself; something like:

```html
<zero-md id="el" src="test/top.md"></zero-md>
<script>
var el = document.querySelector('#el');
el.addEventListener('zero-md-rendered', function() {
  var nodes = el.querySelectorAll('a[href$=".md"]');
  nodes.forEach(function(node) {
    node.href = 'test/' + node.href;
  });
});
</script>
```

**Comment by fbalady-synamedia** [comment] 2020-02-20 18:10
Relative links are preferred because the md may move to different servers, for example, internal company publishing versus external publishing.  I will look at your alternative js code to transform, thanks!

Regarding why the link, although the issue is the same, the primary use case I'm after is linking to an image in an "images" subdirectory using ![]() notation.  That also doesn't work correctly when using relative links.

**Comment by zerodevx** [comment] 2020-02-22 06:27
Thanks for the feedback @fbalady-synamedia - since `zero-md` is due for an update I'll probably add logic for relative link handling in the next release soon. Let's keep this issue open for now - stay tuned!

**Comment by neskk** [comment] 2020-07-30 15:14
I would love if there was a feature that enabled the navigation between different `.md` files.
It would have to intercept the hyperlink click event, and if it was a `.md` file, it would just render its contents in the current active element.
Maybe even an attribute for the `zero-md` tag, where one could specify where you want the links from that render to be open. For instance: having a menu `<zero-md src="menu.md" target="#main">` and having a content area `<zero-md id="main" src="index.md">`.

Just an idea, probably a bit off-topic here ;)

**Comment by zerodevx** [comment] 2020-08-05 17:28
Better handling of relative links is definitely in the pipeline. This is especially true for the use case @fbalady-synamedia described:

> Regarding why the link, although the issue is the same, the primary use case I'm after is linking to an image in an "images" subdirectory using ![]() notation. That also doesn't work correctly when using relative links.

However, in the case of intercepting anchor links to another `.md` file (within the same domain), and doing a re-render, this falls within the realms of client-side routing and SPA, so I'm not sure if it's something people would expect. 

Instead, a gist (or a recipe) like what @neskk posted would work quite well outside the remit of `zero-md` - where you can optionally chain [History API](https://developer.mozilla.org/en-US/docs/Web/API/History_API) `pushState` to update the URL bar if your use-case requires it.

IMO, what `zero-md` needs is a more elegant (and more up-to-date) way that exposes hooks where consumers can subscribe to and extend functionality, customised to their needs, if required. This also goes to my *Long List of Stuff to Change* in the new release. 😅

**Comment by neskk** [comment] 2020-08-05 23:13
> However, in the case of intercepting anchor links to another .md file (within the same domain), and doing a re-render, this falls within the realms of client-side routing and SPA, so I'm not sure if it's something people would expect.

You're probably right and since I didn't explore enough of the Javascript library world, I feel that my request is a bit out of the scope of this project. 😉

**Comment by zerodevx** [comment] 2020-11-02 10:51
It took some time, but following https://github.com/zerodevx/zero-md/issues/22#issue-564789930, relative links in markdown docs are now (finally!) re-written *relative to the `src` url*.

This feature is available in V2. 😄 

Closing this for now! 🎉  Feel free to re-open if something's wrong!

**Closed by zerodevx** 2020-11-02 10:51 UTC
