### ISSUE TITLE
Markdown is currently being loaded twice

### ISSUE THREAD

**Issue by officeSpacePirate** [zerodevx/zero-md#46] opened 2021-02-05 21:39 UTC
Without changes to my implementation of zero-md, multiple environments are now displaying two copies of the generated markdown. I am using:

```{code:html}
<head>
...
  <script type="module" src="https://cdn.jsdelivr.net/gh/zerodevx/zero-md@2/dist/zero-md.min.js"></script>
...
</head>
<body>
...
<div>
    <zero-md src="{path to .md file}">
        <template>
            <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css">
            <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
            <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-blue.min.css" />
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/PrismJS/prism@1/themes/prism.min.css">
            <style>
                :host {
                    top: -32px;
                }
                .markdown-body h1 {
                    font-size: 24px;
                }
                .markdown-body h2 {
                    font-size: 20px;
                }
                .markdown-body h3 {
                    font-size: 16px;
                }
                .markdown-body code {
                    background-color: #f5f5f5;
                    border-radius: 2px;
                    padding: 2px;
                    font-weight: bold;
                    font-size: 14px;
                }
                .markdown-body pre,
                .markdown-body pre code {
                    background-color: #f5f5f5;
                    border-radius: 2px;
                    font-weight: 400;
                    font-size: 14px;
                }
                .markdown-body pre {
                    padding: 8px;
                }
            </style>
        </template>
    </zero-md>
</div>
...
</body>
```

The added styling is to match a material-esque website it's embedded in, but maybe it's no longer compatible after your recent release? Any help is much appreciated.

**Comment by zerodevx** [comment] 2021-02-06 04:47
Ooh it's possible that there's a regression in the latest release that's not caught by unit tests.

> multiple environments are now displaying two copies of the generated markdown

Can you describe the side effects in greater detail? If it's convenient, can you perhaps attach a screenshot?

> The added styling is to match a material-esque website

The added styling should most definitely work, just as it was in the previous version. =/

Lastly, are there are error messages shown in the console?

Thanks!

**Comment by officeSpacePirate** [comment] 2021-02-08 16:24
The result is that a markdown file is being requested and loaded twice in the target div, one after/below the other. There are no console errors, but if you watch the Network in your dev tools the .md file passed to your library is being requested twice. Inspecting the web page, it looks like the `markdown-body` div is added twice in `#shadow-root` on the page. I can't share screenshots of the site in question, but if it'll help I could throw a page together the way I have everything setup and take one.

**Comment by zerodevx** [comment] 2021-02-08 16:51
Hmm I'm not able to reproduce this - https://plnkr.co/edit/suvHkXXTxluLpvdU (try clicking on the "Open preview in separate window" icon). The latest release changed the component initialisation logic so a bug could well be introduced there.

Would you mind re-creating a simple reproduction?

**Comment by zerodevx** [comment] 2021-02-09 08:12
I managed to reproduce this - https://plnkr.co/edit/GX0O59klPiUdEttk ("Refresh live preview" until the issue occurs)

It's a timing issue. In general, rendering can only occur if a) Marked and Prism are loaded; and b) the element is connected. Some frameworks (like in your case) moves the `zero-md` node very early in its lifecycle, thereby causing a disconnect/reconnect. Essentially:

1. Marked and Prism are loading.
2. Element connects, triggering a render.
3. Element disconnects, and reconnects again, triggering another render.
4. Marked and Prism are loaded, causing both renders to run at the same time.
5. A race condition occurs.

Probably the more correct initialisation mechanism will be to shift the initial rendering call into the element constructor to ensure that it's only called once. This also makes sense because if a `zero-md` node is moved in the DOM tree, it does not necessarily mean a re-render should occur. 

I'll push a fix for this and release an update. Thanks for your bug report.

**Closed** 2021-02-09 08:22 UTC
